documented packet 52 and 40
Scrap-Mechanic-Modding/docs pull request #37
Opened 2023-04-08 05:00 UTC by unknown81311

2023-04-08 05:06 UTC, TechnologicNick requested changes

2023-04-08 05:06 UTC, TechnologicNick commented on docs/networking/packets/40-glowstick-effect-removal.mdx
> +- **Bound To**: Client IDK Server
Please add the direction.

2023-04-08 05:06 UTC, TechnologicNick commented on docs/networking/packets/40-glowstick-effect-removal.mdx
> +This packet is sent when the player removes a glowstick effect.
I doubt the devs made a packet specifically for the glowstick effect removal.

2023-04-08 05:06 UTC, TechnologicNick commented on docs/networking/packets/40-glowstick-effect-removal.mdx
> +| 0x02   | Effect ID        | u32        |  |
Add endianness maybe?

2023-04-08 05:06 UTC, TechnologicNick commented on docs/networking/packets/52-lift-level.mdx
> +- **Bound To**: Client IDK Server
Direction pls

2023-04-09 02:46 UTC, ColdMeekly approved these changes
nice

2023-04-09 02:47 UTC, ColdMeekly approved these changes

2023-04-09 14:19 UTC, TechnologicNick approved these changes

2023-04-09 14:20 UTC, merged